import React from 'react';

interface ReportProps {
  partnerName: string;
  market: string;
  totalCalls: number;
  revenueRecovered: number;
  sovereignFee: number; // The 15% Hub Cut
  activeAgents: number;
}

export const PartnerReport: React.FC<ReportProps> = ({
  partnerName,
  market,
  totalCalls,
  revenueRecovered,
  sovereignFee,
  activeAgents
}) => {
  return (
    <div className="p-8 bg-white border border-gray-200 shadow-xl max-w-4xl mx-auto my-10 font-sans">
      {/* Header: Sovereign Branding */}
      <div className="flex justify-between items-start border-b-2 border-gold-500 pb-6 mb-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tighter text-black uppercase">Executive Summary</h1>
          <p className="text-gray-500 mt-1">Global Revenue Workforce Node: {partnerName}</p>
        </div>
        <div className="text-right">
          <div className="bg-black text-white px-4 py-1 text-xs font-bold uppercase tracking-widest">Sovereign Hub</div>
          <p className="text-xs text-gray-400 mt-2">Cycle: December 2025</p>
        </div>
      </div>

      {/* Market Intel */}
      <div className="grid grid-cols-3 gap-6 mb-10">
        <div className="bg-gray-50 p-4 rounded">
          <p className="text-[10px] uppercase text-gray-400 font-bold mb-1">Market Node</p>
          <p className="text-lg font-bold">{market}</p>
        </div>
        <div className="bg-gray-50 p-4 rounded text-center">
          <p className="text-[10px] uppercase text-gray-400 font-bold mb-1">Active AI Workforce</p>
          <p className="text-lg font-bold">{activeAgents} Agents</p>
        </div>
        <div className="bg-gray-50 p-4 rounded text-right">
          <p className="text-[10px] uppercase text-gray-400 font-bold mb-1">Call Volume</p>
          <p className="text-lg font-bold">{totalCalls.toLocaleString()}</p>
        </div>
      </div>

      {/* Financial Settlement Logic */}
      <div className="border-2 border-black p-6 mb-8">
        <h3 className="text-xs font-bold uppercase tracking-widest mb-4 border-b pb-2">Financial Settlement</h3>
        <div className="space-y-4">
          <div className="flex justify-between">
            <span className="text-gray-600">Total Revenue Recovered</span>
            <span className="font-bold">${revenueRecovered.toLocaleString()}</span>
          </div>
          <div className="flex justify-between text-blue-600">
            <span className="font-medium">Sovereign Success Fee (15%)</span>
            <span className="font-bold">-${sovereignFee.toLocaleString()}</span>
          </div>
          <div className="border-t pt-4 flex justify-between text-xl font-black">
            <span>Net Partner Yield</span>
            <span className="text-green-600">${(revenueRecovered - sovereignFee).toLocaleString()}</span>
          </div>
        </div>
      </div>

      {/* Footer / Legal */}
      <div className="text-[9px] text-gray-400 leading-tight">
        <p>This report is generated by the Sovereign Global Financial Hub. 
           Calculations are based on verified conversion scripts and verified call logs. 
           Success fees are non-refundable and automatically processed via Elite tier logic.</p>
      </div>
    </div>
  );
};
