import { Resend } from 'resend';
import { createServerClient } from '@supabase/ssr';
import { cookies } from 'next/headers';
import { NextResponse } from 'next/server';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function GET(request: Request) {
  // 1. Verify the Vercel Cron Secret (Security Infrastructure)
  const authHeader = request.headers.get('authorization');
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return new Response('Unauthorized', { status: 401 });
  }

  const cookieStore = await cookies();
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { cookies: { getAll() { return cookieStore.getAll() } } }
  );

  // 2. Fetch Data from the last 24 hours
  const { data: calls, error } = await supabase
    .from('calls')
    .select('*')
    .gte('created_at', new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString());

  if (error) return NextResponse.json({ error: error.message });

  // 3. Send the Infrastructure Report
  const { data, error: mailError } = await resend.emails.send({
    from: 'FrontDesk Agents <reports@youragency.com>',
    to: ['client@business.com'],
    subject: `Daily AI Performance Report - ${new Date().toLocaleDateString()}`,
    html: `
      <h1>Your AI Front Desk is Active</h1>
      <p>In the last 24 hours, your AI Infrastructure handled <strong>${calls?.length || 0} calls</strong>.</p>
      <ul>
        ${calls?.map(c => `<li>Call from ${c.phone}: ${c.summary}</li>`).join('')}
      </ul>
      <p><em>This report was automatically generated by FrontDesk Agents LLC Infrastructure.</em></p>
    `
  });

  return NextResponse.json({ success: true, delivered: data });
}
