'use client';

import { taxEngine } from '@/lib/market/tax.service';
import { GlobalPricing } from '@/lib/market/pricing';

export default function SovereignInvoice({ subtotal, countryCode }: { subtotal: number, countryCode: string }) {
  const tax = taxEngine.calculate(subtotal, countryCode);
  const market = GlobalPricing[countryCode as keyof typeof GlobalPricing] || GlobalPricing.WESTERN;

  return (
    <div className="p-8 bg-white text-black rounded-3xl font-mono shadow-2xl max-w-md mx-auto">
      <div className="flex justify-between border-b-2 border-black pb-4 mb-6">
        <h2 className="font-black uppercase tracking-tighter">Tax Invoice</h2>
        <span className="text-[10px] font-bold">NODE_{countryCode}_PRIMARY</span>
      </div>
      <div className="space-y-2 mb-8">
        <div className="flex justify-between text-sm">
          <span>Infrastructure Subscription</span>
          <span>{market.symbol}{subtotal.toFixed(2)}</span>
        </div>
        <div className="flex justify-between text-sm text-slate-500 italic">
          <span>{tax.taxName} ({tax.rate * 100}%)</span>
          <span>{market.symbol}{tax.amount.toFixed(2)}</span>
        </div>
      </div>
      <div className="flex justify-between border-t-2 border-black pt-4">
        <span className="font-black uppercase">Total ({market.currency})</span>
        <span className="font-black text-xl">{market.symbol}{tax.total.toFixed(2)}</span>
      </div>
      <p className="mt-8 text-[8px] text-slate-400 leading-tight">
        Compliance Note: This invoice is generated by the FrontDesk Agents Global Node in accordance with {tax.taxName} regulations for {countryCode}.
      </p>
    </div>
  );
}
